apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: default   # Add this line to specify the default namespace
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
    - nodePort: 31000
      protocol: TCP
      port: 8080
